# AUTH API

# REGISTER
# POST http://localhost:5000/register
# Content-Type: application/json

# {
#   "email": "test@example.com",
#   "password": "password123",
#   "confirmPassword": "password123",
#   "role": "user"
# }

# Login
# POST http://localhost:5000/login
# Content-Type: application/json

# {
#   "email": "test@example.com",
#   "password": "password123"
# }

# CONTACT
# POST http://localhost:5000/api/submit
# Content-Type: application/json

# {
#   "fullname": "John Doe",
#   "email": "johndoe@example.com",
#   "message": "Hello, this is a test message!"
# }

# ROUTES API

# Add bus routes
# POST http://localhost:5001/api/routes
# Content-Type: application/json

# {
#   "origin": "Minus cupidatat irur",
#   "destination": "Sit aliquip dolorib",
#   "startTime": "04:31 AM",
#   "endTime": "11:00 AM",
#   "departureTime": "11:28 AM",
#   "departureDate": "2010-04-15",
#   "pricePerSeat": 99,
#   "vehicleType": "Coach",
#   "facilities": ["Eum ut aliqua Maior"],
#   "totalSeats": 32
# }

# Get all available bus routes
# GET	http://localhost:5001/api/routes


# Get details of a specific bus route by ID
# GET	http://localhost:5001/api/routes/:id	
# GET	http://localhost:5001/api/routes/67e41ea7f72030382d5afe59	


# Update an existing bus route (Admin)
# PUT	http://localhost:5001/api/routes/:id	
# PUT	http://localhost:5001/api/routes/67e41ea7f72030382d5afe59
# Content-Type: application/json

# {
#   "origin": "Updated Origin",
#   "destination": "Updated Destination",
#   "startTime": "06:00 AM",
#   "endTime": "02:00 PM",
#   "departureTime": "06:00 AM",
#   "departureDate": "2025-04-10",
#   "pricePerSeat": 80,
#   "vehicleType": "Luxury Bus",
#   "facilities": ["WiFi", "Reclining Seats"],
#   "totalSeats": 50
# }

# Delete a bus route (Admin)
# DELETE	http://localhost:5001/api/routes/:id	
# DELETE	http://localhost:5001/api/routes/67e41ea7f72030382d5afe59	


# User Bookings		

//Book a seat using personal information
# POST http://localhost:5003/api/routes/book-seats
# Content-Type: application/json

# {
#   "userId": "67e023f01b60c22c93485e35",
#   "routeId": "67e41ea7f72030382d5afe59",
#   "seats": ["A1", "A2", "A3"],
#   "departureDate": "2025-03-28",
#   "passengerInfo": {
#     "name": "John Doe",
#     "phone": "1234567890",
#     "email": "johndoe@example.com"
#   },
#   "totalPrice": 1000
# }

# Get bookings of a specific user
# GET	http://localhost:5001/api/routes/user-bookings/:userId
# GET	http://localhost:5001/api/routes/user-bookings/67e026d51b60c22c93485e40


# Get details of a specific booking
# DELETE	http://localhost:5003/api/routes/bookings/:id
# DELETE	http://localhost:5003/api/routes/bookings/67e4e5fe94ff410965fe77d3


#Get all bookings
# GET http://localhost:5003/api/routes/bookings
